[project]
name = "just-type-it"
version = "0.1.0"
description = "A CLI typing tutor with a slick TUI interface"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
just-type-it = "just_type_it:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
